### ISSUE TITLE
Only see csv file for Chapter 1, no workbook?

### ISSUE THREAD

**Issue by karmamule** [PacktPublishing/Mastering-Tableau-2021#1]
In Chapter 1 of your book you refer to providing a worksheet, but I'm only seeing a single CSV file under the Chapter 1 folder. Is there a missing file or is that worksheet elsewhere in the repo?

Thanks for any info you can provide!

**Comment by MMarleen** [comment]
Hey @karmamule, I will check with Packt but for now, you can also get the dashboards from here: https://public.tableau.com/profile/marleen.meier#!/?newProfile=&activeTab=0. 
I hope this helps!

**Comment by karmamule** [comment]
Thank you very much!
